name: bball
channels:
  - defaults
dependencies:
  - jupyter 
  - matplotlib
  - notebook
  - numpy
  - pandas 
  - pip
  - python=3.7
  - pip:
    # works for regular pip packages
    - git+https://github.com/DEAP/deap@master

